#----------------------------------------------------------------------
# This file was generated by generate_icon.py
# It contains base64-encoded PNG icons for use with PySide6
#

import base64
from PySide6.QtGui import QPixmap, QIcon
from PySide6.QtCore import QByteArray


def get_icon_from_base64(data_str):
    """Convert base64 string to QIcon.
    
    Args:
        data_str: Base64-encoded PNG data
        
    Returns:
        QIcon: Icon object or empty QIcon on error
    """
    try:
        byte_array = QByteArray.fromBase64(data_str.encode('ascii'))
        pixmap = QPixmap()
        pixmap.loadFromData(byte_array)
        return QIcon(pixmap)
    except Exception as e:
        print(f"Error loading icon: {e}")
        return QIcon()


# Icon catalog - maps icon names to base64-encoded PNG data
ICON_DATA = {
    'database_24dp_1976d2_fill0_wght400_grad0_opsz24': 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAByUlEQVRIS2NkoDFgpLH5DANrgVjZ' \
    'pWgmBoZqoCs0sfn0/3+Ga0Dc+rJHbxmukMD0Qe5tdkmO78+AfhMiKfj+M7x7/uOJFMNkr5/I+lAs' \
    'ECu9Ys3M+O8ITMF/BoYT//7+7XzVa7gBm2VAHwYwMzCWMDD8t4br+f3P/EW/wSkYH8UCybJLQDOB' \
    'yv8x1L3o0WsmxQcSpZdLGBn/d4P0PO/Sg5uL3YL/DPUvuvWaSLKg7GIpIwNjF1EWEB1EJRcCmRiZ' \
    'ShkZGSyRHUPQB0DFb4FYmBQf/Gf4/xroA1GifABzgUTZxSzG/wzNDIyMWFMUMMJe/v//v+Zlt/4c' \
    'kMGwOCToA2QFpPiCaAu+/mYW/tSv/Y4Uw6WKb4r8Z/75mqgggkfyv//Tvv1lqcVlmXjJRTEmRoZW' \
    'YBCmjEYyUdFBdCT//c8U/6pbZxFRpkIViZdezmdi/D8BbySLll/yZPnPsA3J4N3/Gf61v+gy2I+9' \
    'sLvsyvT/fzUwJ9vD5P/9Y3AFFt97sBZ2IEGRgjOSrGxs94BMDlJ8wPD///f/P/7Kv5hsBE6qOC1A' \
    'lpQovZQALCErGRgY1XBYdhNYRAB9qL8Ql2MGtsokKYhwKKa5DwDp5uEZUFexPQAAAABJRU5ErkJg' \
    'gg==',
    'globe_24dp_1976d2_fill0_wght400_grad0_opsz24': 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAACR0lEQVRIS71VTWsTQRh+ZyepkIMK' \
    'xiTtSSw0JeomQcEaeqh/QJB6Uw8ieBXaJOYvuNvWfyCCPQe8ePXkJ5WYXUK1lfaYbRtPfoHZnXFG' \
    '3WV3djYThbqnZOfd52vedwbBIT/okPFBSXCy1ati4rYRoFNhMRRgx3PJtYO1SmeUyESC7N1uMX0E' \
    'vR/HoUtTMwdmaVtWKyXIN6zHGoIbvz+g3yjQy45ReeMD5Br2NEb0Y8QRgkfOff2WSBIjYOBtBn6V' \
    'Fw49uDBY1d+KH002LZZQ/GFC2o5RXgyvRAgKy70Swl6PF/SHXzLwoPbdL843u3MaoJeqyIZAZwdG' \
    '+YNfFyHwlXnUm983q8/DYEmqZYR9Qw9wgx/ZlnU+TWCDef/sGPrRcWOREYSjDQiYQt4xRY9AbX9F' \
    'j0XxNw4ohU3H1EucPEzwa+PC9kblrSL0cf4/QZJqZnuX2T4dzELduoQ1eBGZBQ+fCbrwz0bHHKja' \
    'UBWhH10sokKzuyueN/Jhgh3WZdOytULdXkAafQaUbvfN8kxkk3P37BqmNNL7SW6SXDD1X9k3GULo' \
    '3N5K+XWEgP9RdYZPKCPItuyFNGHqhU6MTHK+3j2rachWTae4PnVnI0OPT3D18ANQ6ZNxblN6VPCX' \
    'hab1hLFeEUGSYmGiLjJRr3i98rDzQScb1jobwethEpEgt9SpaSn8lIk5xusIhfU9U78pCku8cE4s' \
    'W7MTGAKro9p36JLiYK2yJatRX5lL76opjB4CQhUBoOO65PY/X5mqgRt3XelgXKCkup88eecZ4KAG' \
    'ogAAAABJRU5ErkJggg==',
    'home_app_logo_24dp_1976d2_fill0_wght400_grad0_opsz24': 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAABdElEQVRIS2NkoDFgpLH5DIPHAonS' \
    'S8cYGRksQT7+z8Bw6EWXnj0xvifKBxJlF+8zMjAqIBv4n+H/gxdd+oqELCFoAbLhz+8zs4MMlFT8' \
    '+xPiE8KW4LUAxfAPv9gYZpn8BltQdgkYShBAyBKcFmC4fLX2LzTD3wL5woQswWoBIZcDnf8CGMmS' \
    'DA3/mSS/Xf6LzxIMCwgZDgua5116EL2h/5klFS//wWUJigXAsF0PVBgAUgyOUPRg+f//A9hQRkYB' \
    'sBqYJQ3/WYA+AccPMFLWP+/WC4I5BN0CcOQ95wIa3oAR5u+BBgpB4+EdkBZEteQqm+Q3SOqCWwxy' \
    'C8wm5AiEKYCnFqDLn3frgw2EAcnSi+/RfQJTT7IFyBqIcdDgswDZ1djY6EFKsg9oZgEhg9HliY9k' \
    'pDxAtCWhwGQKLQRxBhEwF+8AFsvuRBuKRSGw8NsCLMZ9sWY0kKBE6cUVjIyM4eRYAjR8BdDwSGS9' \
    'BOsDciwaXhYAAC5+8hlMv//HAAAAAElFTkSuQmCC',
    'home_app_logo_48dp_1976d2_fill0_wght400_grad0_opsz48': 'iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAADj0lEQVRoQ+2YTWgTURDH521ixHjp' \
    'pc0HLVYrHrTJVuhVPOjZKqjVqnjzJoia3JSqpyYpevYkgp8VUcSDoBfPoiQBQVBatc1uShU9KJg2' \
    'O87W7na72Y+X7JJQ2XdL3pt5/9/MvNm3y2CdD7bO9UMA0OkMBhn4LzMQz5T2MgbPCW7zMiDCHxCU' \
    'EWli6IXfwL6XUCJb/ADAdtgInZVy6T4/IXwFiGdLc+Qw6SgQcUHKi91+QfgGkMiWvpKoXk0YKjgu' \
    'F8Qr6u9ktnQVAS7pc4A/5ZzY5QeELwAU+Qo5ShgEnaRSuWMUGM8WTzNgt/T/fMqEZ4B4tkziUReP' \
    'ChuVC6mHVtGNZcqjAsP7fkJ4AqDIS+QgrgliCpyoFNJ37UqDyowqyTQ8ZqJlAIo8icdV8SiMVfKD' \
    '95oSrx+K1g92SwAUeZkMY9r+CuJYNS9yi8dafStGhAEB2Euv5dQ0QIN4JhyvTgyu1rUpBeayUcXL' \
    'N3bPqMti2eI+rxBNAZD4Khn06JFnSOJFbvFQD/dLkzs/Gxm9QnADUCSrtLEuHgGPUC9/xFvzioLb' \
    'qgVx2mp9IlPcA4y9bqWcuABI/Dw515+eCrJj1XzqAa94bZ0UDW2E8V01yxbbYjm5ApjFI6M+P2Hd' \
    '51Vhlq3SoFj6UYvAzeFFvyAcARquB02KVw+sKpRFQmtKR4qmNsA4W+KCAHC8ANoCxC6WRgQBnqy2' \
    'ajgq59NTvGVj7Dbxc+/6GyCmU2GYYnUeCEWBg9VC+qnVWlsAiv4vMoguRxDgWiWXvtyKeM3GEiKX' \
    'dti/fIpeJG6v2P+mu9W/dwvTcALQH/tkzLVO9V1Htn0+n/pktVlPpjwQYvjROCflUgKFqPGKYTpP' \
    'dhq4hNkZOz2k7LLVTCaM/n0HaEW8BpW48H4LhJZm1maiMcttAzAeWLvIm/83Z8Iqwm0DcDojTkBu' \
    'At3mVxqM9RZuxm7zPJlw8+E2HwBoUV73JcRTLm5rOnqI3cTxzAcA5ijxdACeyHpZw6PB01XCizge' \
    '2wBAi1JtUen9dn1ojidqfq1Jni/3YRi/uLVq2xKib5lT9C3zsOaA1WvdlcnhBb8EOvlJnnkTxa6I' \
    '+j6yPBDxmZwXD1jZuL1SWt7T2wFh3MPpQekIED/7tpttCqtfJDo2/gD2fc+Js3YCXL9KqIaJTOkx' \
    'vVceaicFpf6VnEvvd9uTC8DNSSfnA4BORl/dO8hAkAGPEfgL8lIZT91TCwEAAAAASUVORK5CYII=',
    'logout_24dp_1976d2_fill0_wght400_grad0_opsz24': 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAxElEQVRIS2NkoDFgpLH5DPS1QLzs' \
    'ogUTA+NxfL563qVHkqNQFEuWXfpPKMioYgGphuBzFFYfDBoLJEsvFf5nZOR70aXbiMsXZPtAoOC8' \
    'ACcb83uQwf8ZGBtwWUK2BSCDRUovGrEyMp7FZwlFFoAMFi6+YsrG/O8ULkuIsoCY5AuLA/TgGhwW' \
    '4EvnVAkiXBbQNJIFy+/yc/z/+oGmyZSmGY1QoQiTJyoVEWsYNnX0La7FSi5ZMjMxHKNZhUNJUBBV' \
    'mg5JCwAP2oYZNo+ptAAAAABJRU5ErkJggg==',
    'sensors_24dp_1976d2_fill0_wght400_grad0_opsz24': 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAACEElEQVRIS2NkoDFgpLH5DKMWEAxh' \
    'jCASL720jpHh/7EX3fo9BHUjKZAovVzCwPjP8kWXfjCyPhQLxIsuWjCxMB4HKXj++wsXQ7/Vd6Is' \
    'KTzGKcnK8w2s9i+DyfNevbMwfSgWSJZd+g+S+M/wPxTokjVEGQ5VJF56OZyJ8f8KsOO69ODmwhkS' \
    'pZfsGRkZDvz///8vMHhYQAolSi/+AVpW87LboAObZeJlF6sZ/zM0IqtnZGRk/vOXwf51r94hkB6E' \
    'BWWXHgI5ckDzvV90G24TL72Qy8TINAndRcgWIfk4G+jjaRLll70Z///f8v8/w/0X3XpKKBbAFMO8' \
    'B+P/ZPgv+65L/wnQtRZMDJD4+feP2eJlj/ZJoaJTsuwsHI+QHYFuDtwHuCxAtxDmA3RxXPyBt+A3' \
    'A5v0my6NZ2IllyyZmRiOgYPoz3/Ll336J4RyL8qwczI+JiqIJMou3QZ6R+Xvf0b3V926u8TKLkUz' \
    'MzAsQU5V6CkJmPL+AFMe879/DNEve/SWSZQAI5kJHMnXgJGsjZaKLpgxMjCdBGaE3y+69NjAybTs' \
    '0m+gBfUvu/XbcCZTBsZ6hPqLvxkZGFn+/GE2et2nfR7FAhAHkez+Ob3oMthPUkYruejExMS4F2dG' \
    'A0mIl1zUASq6DFZEZlHxi4FR622X7nWY4zAKO2Du3QiUPEyTwo6UICFW7WiNRjCkaB5EADhnECh3' \
    'Y5WdAAAAAElFTkSuQmCC',
    'settings_24dp_1976d2_fill0_wght400_grad0_opsz24': 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAACsElEQVRIS71VTWgTQRR+bxs0RkWh' \
    'Sja95SDWQzZBsaAnSwU9eRH8OdmTKCoodrcKVtPWgyYBhVbRm3pRwYtHMbVHsYIxm0tu7anZSgWF' \
    'Vg00M36bdEN+Jm3AxpwyM2++73vvfW+WqcM/7jA+tUUQsmypElJIGOveXzfABd5Qgp74fGA+3vOr' \
    'VrFH4CluXHuxqrtNGeDyH1zYTJLShbn8cT289xMTH3BBGgmw9aUwm+/Tw73vADSAdREx/lpxdQRB' \
    'KzugEadV9ZaSPjtJo8890017hpkOquIEyaMLieiUd1ZH4KVeYi3GJM5pkq4h8DtU7VKBhazcIpHs' \
    'FkwPhCi98HFXpjZT93+VQDezj5n5Iuyy7CSMbSrAoGWfZ5I+J2A8oTiLxhgIXMZeANk+QraX6wks' \
    '+wfYdribJUEXvqWMpx6APpw7xVK+rgWEkNsQMu7tBYeyZzSNX7prnP3E2c46gnJtLXsCJGXm2pq3' \
    'tOnvLX6a2FNET6bRkyOr4JMAv6LsgbsZMu1bKNw4CBJIczhkZk8S8xtl40mOOoloXLdyCZTOhPSR' \
    'QtK4WxvbZFN96OsIa9qYlJxykhETzjoBZ71VEgiOO6nIqG5lU7DydSHp5kLSuNeSAKlOItVLlRLJ' \
    'D04y6nq79SR7JbLs9OocuPcgLGo2lQj1rzZZCHl2IRV9VW2gmTutsayuKwLEHScZG1M1GeaEtSNl' \
    'a2+oTSFyCYBb4aL7aPSNJhdVB21lJcY+36BGdBUaFqFmt6oHiMegUTcG4qGQXc99XGo9aC7Amk8F' \
    'yQwcs7/itGwGzoqpSDFDhzFDH1vb1LKLONyENKec2fyxULh3BusycONjV56VufwhPbzvPWzajztL' \
    'KM32NW36L881DU776Vm/+xpXf///g9OimZ39ZKpI291rq0Ttgqni/gJg6kEoQjZCgQAAAABJRU5E' \
    'rkJggg==',
    'toggle_off_24dp_1976d2_fill0_wght400_grad0_opsz24': 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAABSElEQVRIS2NkoDFgpLH5DKMWEAxh' \
    '+geRZMmlIgYmhl6CTsOm4D9D0fNuvX5kKRQfSJZd+k+WwWiannfpwc2FM5AN///rr+KLCYYPSLFM' \
    'vOSiIhMT4z2YHpglYAskSi+VMTIydILYIAmJsksrgRJhYMX/GZYBvR1NrGUwh/77/7/gZbf+RLAF' \
    'MMGffxjl2JgZpjIy/vdFMfA/w0agJQHEWCJRcV6B8R/zfZhjUSwAuR5XPCCHKyGLYGaA9NDXgi/M' \
    'rCLcf38tZWRgdEd25X+G/1tedOmjBhsObwAjWwwY2S9Rgki89FIFEyNDOzySSy+uYGRkDIeasRzo' \
    '1ShCwQKTh0cyw//Cl136E7AmU4a/LArPe7UeEmsoOCVWXAdG7m9w5MIcCqLpl9HgXqSgqPj3nxGY' \
    '9nUnIvuc/oUdKeFOjNpRHxAMJZoHEQDDK4UZwS/yHgAAAABJRU5ErkJggg==',
    'toggle_on_24dp_1976d2_fill0_wght400_grad0_opsz24': 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAABQUlEQVRIS2NkoDFgpLH5DKMWEAxh' \
    '+geRZMmlIgYmhl6CTsOm4D9D0fNuvX5kKRQfSJZd+k+WwWiannfpwc2FM5AN///rr+KLCYYPSLFM' \
    'vOSiIhMT4z2YHpglYAskSi+VMTIydILYyLYTskCi7NJKoAFhYHX/GZYBgyca5tB///8XvOzWnwi2' \
    'ACb48w+j3Ls+3ceEDIY46vImRsb/vihq/zNs/M/8t4DxH/N9mGNRLCDF9bjiC2QGTA7Epq8FX5hZ' \
    'RT63a74lKojKLu5gZGB0R1b7n+H/lv//GJKBkf0SJYjESy9VMDEytJMcyaUXVzAyMoZDLVkODJIo' \
    'eCQz/C982aU/AWsyZfjLovC8V+shMT6BqZGouK7A+O83OHKRHUq/jAazmZKi4t9/RmDa152I7HP6' \
    'F3akhDsxakd9QDCUaB5EAOcMiRnLYc5QAAAAAElFTkSuQmCC',
    'update_24dp_1976d2_fill0_wght400_grad0_opsz24': 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAACIElEQVRIS91VPUscURS9b3Y3Zkli' \
    'E3GcWClstdkxxVrYWSmEtAo2CfgHVHCHlIIWOhsx/yCgpZWFKCrYWURM3NnGQrCJ7KiBINH9ctfn' \
    'eYsjs8PMG0OQBB8Mw8x7955z7tdj9MCLPbB/+vcA6kerm9VphTF63aSW09bFdXXk93z6pywKwQqG' \
    'eKSjK1/CgZjMASe6tM3UCyLGNcPCJ1HB1O/8+gK8nNjvfBJTfjiO+TWN2p/0L24gdTI3rihswfl3' \
    'cVlqe/4s3lAjB5jiilbM18VB0Fm1Tf2dTIGWyX0nxt64z0gBYFCEQRzeNwpZfdBt6BcCsd+RsXLI' \
    'ke6cDQSA7HbIPvHKdAy9AM63V2EgAJh8BZPeOrH3p2ZqyWv41wBBIQhScJ8mbaqi/wAgX0JtPQXz' \
    'CuIs3qHrjxQIb1rGKmPAtKDKKqiyJpDQRkOSd5HkNOf8g53tWQyiB0dl7LXgqUKJeItSNWA7h97Z' \
    'Q++kHdsmBerkIcq0GFimnp6ooMNn0OHTDWW3Y6KmRBJns8lDX4BbJudg0sqJr9lmz9vQIAv2hrUD' \
    'pn2YR+WCmYq7bXxnkauBNhGCARkIQrMNQv2N5jw6iNLycGPMBCoQG23Gt1cxih47h6DGgJqs21DN' \
    '5MYUxj47/2o8op1lk7aXjPTCuZtL0jjxYuFIb6Vl3Bo+K/RGUyesbiXK1zEAE257kaMKuxr5NZc+' \
    'l+GHAtwnyY8b4AaWfuAZx7C1rQAAAABJRU5ErkJggg==',
}


def get_icon(name):
    """Get QIcon by name from the catalog.
    
    Args:
        name: Icon name from catalog
        
    Returns:
        QIcon: Icon object or empty QIcon if not found
    """
    if name in ICON_DATA:
        return get_icon_from_base64(ICON_DATA[name])
    print(f"Warning: Icon '{name}' not found in catalog")
    return QIcon()

