#----------------------------------------------------------------------
# This file was generated by generate_icon.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

catalog = {}
index = []

database_24dp_1976d2_fill0_wght400_grad0_opsz24 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAByUlEQVRIS2NkoDFgpLH5DANr'
    b'gVjZpWgmBoZqoCs0sfn0/3+Ga0Dc+rJHbxmukMD0Qe5tdkmO78+AfhMiKfj+M7x7/uOJFMNk'
    b'r5/I+lAsECu9Ys3M+O8ITMF/BoYT//7+7XzVa7gBm2VAHwYwMzCWMDD8t4br+f3P/EW/wSkY'
    b'H8UCybJLQDOByv8x1L3o0WsmxQcSpZdLGBn/d4P0PO/Sg5uL3YL/DPUvuvWaSLKg7GIpIwNj'
    b'F1EWEB1EJRcCmRiZShkZGSyRHUPQB0DFb4FYmBQf/Gf4/xroA1GifABzgUTZxSzG/wzNDIyM'
    b'WFMUMMJe/v//v+Zlt/4ckMGwOCToA2QFpPiCaAu+/mYW/tSv/Y4Uw6WKb4r8Z/75mqgggkfy'
    b'v//Tvv1lqcVlmXjJRTEmRoZWYBCmjEYyUdFBdCT//c8U/6pbZxFRpkIViZdezmdi/D8BbySL'
    b'll/yZPnPsA3J4N3/Gf61v+gy2I+9sLvsyvT/fzUwJ9vD5P/9Y3AFFt97sBZ2IEGRgjOSrGxs'
    b'94BMDlJ8wPD///f/P/7Kv5hsBE6qOC1AlpQovZQALCErGRgY1XBYdhNYRAB9qL8Ql2MGtsok'
    b'KYhwKKa5DwDp5uEZUFexPQAAAABJRU5ErkJggg==')
index.append('database_24dp_1976d2_fill0_wght400_grad0_opsz24')
catalog['database_24dp_1976d2_fill0_wght400_grad0_opsz24'] = database_24dp_1976d2_fill0_wght400_grad0_opsz24

#----------------------------------------------------------------------
globe_24dp_1976d2_fill0_wght400_grad0_opsz24 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAACR0lEQVRIS71VTWsTQRh+Zyep'
    b'kIMKxiTtSSw0JeomQcEaeqh/QJB6Uw8ieBXaJOYvuNvWfyCCPQe8ePXkJ5WYXUK1lfaYbRtP'
    b'foHZnXFG3WV3djYThbqnZOfd52vedwbBIT/okPFBSXCy1ati4rYRoFNhMRRgx3PJtYO1SmeU'
    b'yESC7N1uMX0EvR/HoUtTMwdmaVtWKyXIN6zHGoIbvz+g3yjQy45ReeMD5Br2NEb0Y8QRgkfO'
    b'ff2WSBIjYOBtBn6VFw49uDBY1d+KH002LZZQ/GFC2o5RXgyvRAgKy70Swl6PF/SHXzLwoPbd'
    b'L843u3MaoJeqyIZAZwdG+YNfFyHwlXnUm983q8/DYEmqZYR9Qw9wgx/ZlnU+TWCDef/sGPrR'
    b'cWOREYSjDQiYQt4xRY9AbX9Fj0XxNw4ohU3H1EucPEzwa+PC9kblrSL0cf4/QZJqZnuX2T4d'
    b'zELduoQ1eBGZBQ+fCbrwz0bHHKjaUBWhH10sokKzuyueN/Jhgh3WZdOytULdXkAafQaUbvfN'
    b'8kxkk3P37BqmNNL7SW6SXDD1X9k3GULo3N5K+XWEgP9RdYZPKCPItuyFNGHqhU6MTHK+3j2r'
    b'achWTae4PnVnI0OPT3D18ANQ6ZNxblN6VPCXhab1hLFeEUGSYmGiLjJRr3i98rDzQScb1job'
    b'wethEpEgt9SpaSn8lIk5xusIhfU9U78pCku8cE4sW7MTGAKro9p36JLiYK2yJatRX5lL76op'
    b'jB4CQhUBoOO65PY/X5mqgRt3XelgXKCkup88eecZ4KAGogAAAABJRU5ErkJggg==')
index.append('globe_24dp_1976d2_fill0_wght400_grad0_opsz24')
catalog['globe_24dp_1976d2_fill0_wght400_grad0_opsz24'] = globe_24dp_1976d2_fill0_wght400_grad0_opsz24

#----------------------------------------------------------------------
home_app_logo_24dp_1976d2_fill0_wght400_grad0_opsz24 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAABdElEQVRIS2NkoDFgpLH5DIPH'
    b'AonSS8cYGRksQT7+z8Bw6EWXnj0xvifKBxJlF+8zMjAqIBv4n+H/gxdd+oqELCFoAbLhz+8z'
    b's4MMlFT8+xPiE8KW4LUAxfAPv9gYZpn8BltQdgkYShBAyBKcFmC4fLX2LzTD3wL5woQswWoB'
    b'IZcDnf8CGMmSDA3/mSS/Xf6LzxIMCwgZDgua5116EL2h/5klFS//wWUJigXAsF0PVBgAUgyO'
    b'UPRg+f//A9hQRkYBsBqYJQ3/WYA+AccPMFLWP+/WC4I5BN0CcOQ95wIa3oAR5u+BBgpB4+Ed'
    b'kBZEteQqm+Q3SOqCWwxyC8wm5AiEKYCnFqDLn3frgw2EAcnSi+/RfQJTT7IFyBqIcdDgswDZ'
    b'1djY6EFKsg9oZgEhg9HliY9kpDxAtCWhwGQKLQRxBhEwF+8AFsvuRBuKRSGw8NsCLMZ9sWY0'
    b'kKBE6cUVjIyM4eRYAjR8BdDwSGS9BOsDciwaXhYAAC5+8hlMv//HAAAAAElFTkSuQmCC')
index.append('home_app_logo_24dp_1976d2_fill0_wght400_grad0_opsz24')
catalog['home_app_logo_24dp_1976d2_fill0_wght400_grad0_opsz24'] = home_app_logo_24dp_1976d2_fill0_wght400_grad0_opsz24

#----------------------------------------------------------------------
logout_24dp_1976d2_fill0_wght400_grad0_opsz24 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAxElEQVRIS2NkoDFgpLH5DPS1'
    b'QLzsogUTA+NxfL563qVHkqNQFEuWXfpPKMioYgGphuBzFFYfDBoLJEsvFf5nZOR70aXbiMsX'
    b'ZPtAoOC8ACcb83uQwf8ZGBtwWUK2BSCDRUovGrEyMp7FZwlFFoAMFi6+YsrG/O8ULkuIsoCY'
    b'5AuLA/TgGhwW4EvnVAkiXBbQNJIFy+/yc/z/+oGmyZSmGY1QoQiTJyoVEWsYNnX0La7FSi5Z'
    b'MjMxHKNZhUNJUBBVmg5JCwAP2oYZNo+ptAAAAABJRU5ErkJggg==')
index.append('logout_24dp_1976d2_fill0_wght400_grad0_opsz24')
catalog['logout_24dp_1976d2_fill0_wght400_grad0_opsz24'] = logout_24dp_1976d2_fill0_wght400_grad0_opsz24

#----------------------------------------------------------------------
sensors_24dp_1976d2_fill0_wght400_grad0_opsz24 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAACEElEQVRIS2NkoDFgpLH5DKMW'
    b'EAxhjCASL720jpHh/7EX3fo9BHUjKZAovVzCwPjP8kWXfjCyPhQLxIsuWjCxMB4HKXj++wsX'
    b'Q7/Vd6IsKTzGKcnK8w2s9i+DyfNevbMwfSgWSJZd+g+S+M/wPxTokjVEGQ5VJF56OZyJ8f8K'
    b'sOO69ODmwhkSpZfsGRkZDvz///8vMHhYQAolSi/+AVpW87LboAObZeJlF6sZ/zM0IqtnZGRk'
    b'/vOXwf51r94hkB6EBWWXHgI5ckDzvV90G24TL72Qy8TINAndRcgWIfk4G+jjaRLll70Z///f'
    b'8v8/w/0X3XpKKBbAFMO8B+P/ZPgv+65L/wnQtRZMDJD4+feP2eJlj/ZJoaJTsuwsHI+QHYFu'
    b'DtwHuCxAtxDmA3RxXPyBt+A3A5v0my6NZ2IllyyZmRiOgYPoz3/Ll336J4RyL8qwczI+JiqI'
    b'JMou3QZ6R+Xvf0b3V926u8TKLkUzMzAsQU5V6CkJmPL+AFMe879/DNEve/SWSZQAI5kJHMnX'
    b'gJGsjZaKLpgxMjCdBGaE3y+69NjAybTs0m+gBfUvu/XbcCZTBsZ6hPqLvxkZGFn+/GE2et2n'
    b'fR7FAhAHkez+Ob3oMthPUkYruejExMS4F2dGA0mIl1zUASq6DFZEZlHxi4FR622X7nWY4zAK'
    b'O2Du3QiUPEyTwo6UICFW7WiNRjCkaB5EADhnECh3Y5WdAAAAAElFTkSuQmCC')
index.append('sensors_24dp_1976d2_fill0_wght400_grad0_opsz24')
catalog['sensors_24dp_1976d2_fill0_wght400_grad0_opsz24'] = sensors_24dp_1976d2_fill0_wght400_grad0_opsz24

#----------------------------------------------------------------------
settings_24dp_1976d2_fill0_wght400_grad0_opsz24 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAACsElEQVRIS71VTWgTQRR+bxs0'
    b'RkWhSja95SDWQzZBsaAnSwU9eRH8OdmTKCoodrcKVtPWgyYBhVbRm3pRwYtHMbVHsYIxm0tu'
    b'7anZSgWFVg00M36bdEN+Jm3AxpwyM2++73vvfW+WqcM/7jA+tUUQsmypElJIGOveXzfABd5Q'
    b'gp74fGA+3vOrVrFH4CluXHuxqrtNGeDyH1zYTJLShbn8cT289xMTH3BBGgmw9aUwm+/Tw73v'
    b'ADSAdREx/lpxdQRBKzugEadV9ZaSPjtJo8890017hpkOquIEyaMLieiUd1ZH4KVeYi3GJM5p'
    b'kq4h8DtU7VKBhazcIpHsFkwPhCi98HFXpjZT93+VQDezj5n5Iuyy7CSMbSrAoGWfZ5I+J2A8'
    b'oTiLxhgIXMZeANk+QraX6wks+wfYdribJUEXvqWMpx6APpw7xVK+rgWEkNsQMu7tBYeyZzSN'
    b'X7prnP3E2c46gnJtLXsCJGXm2pq3tOnvLX6a2FNET6bRkyOr4JMAv6LsgbsZMu1bKNw4CBJI'
    b'czhkZk8S8xtl40mOOoloXLdyCZTOhPSRQtK4WxvbZFN96OsIa9qYlJxykhETzjoBZ71VEgiO'
    b'O6nIqG5lU7DydSHp5kLSuNeSAKlOItVLlRLJD04y6nq79SR7JbLs9OocuPcgLGo2lQj1rzZZ'
    b'CHl2IRV9VW2gmTutsayuKwLEHScZG1M1GeaEtSNla2+oTSFyCYBb4aL7aPSNJhdVB21lJcY+'
    b'36BGdBUaFqFmt6oHiMegUTcG4qGQXc99XGo9aC7Amk8FyQwcs7/itGwGzoqpSDFDhzFDH1vb'
    b'1LKLONyENKec2fyxULh3BusycONjV56VufwhPbzvPWzajztLKM32NW36L881DU776Vm/+xpX'
    b'f///g9OimZ39ZKpI291rq0Ttgqni/gJg6kEoQjZCgQAAAABJRU5ErkJggg==')
index.append('settings_24dp_1976d2_fill0_wght400_grad0_opsz24')
catalog['settings_24dp_1976d2_fill0_wght400_grad0_opsz24'] = settings_24dp_1976d2_fill0_wght400_grad0_opsz24

#----------------------------------------------------------------------
toggle_off_24dp_1976d2_fill0_wght400_grad0_opsz24 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAABSElEQVRIS2NkoDFgpLH5DKMW'
    b'EAxh+geRZMmlIgYmhl6CTsOm4D9D0fNuvX5kKRQfSJZd+k+WwWiannfpwc2FM5AN///rr+KL'
    b'CYYPSLFMvOSiIhMT4z2YHpglYAskSi+VMTIydILYIAmJsksrgRJhYMX/GZYBvR1NrGUwh/77'
    b'/7/gZbf+RLAFMMGffxjl2JgZpjIy/vdFMfA/w0agJQHEWCJRcV6B8R/zfZhjUSwAuR5XPCCH'
    b'KyGLYGaA9NDXgi/MrCLcf38tZWRgdEd25X+G/1tedOmjBhsObwAjWwwY2S9Rgki89FIFEyND'
    b'OzySSy+uYGRkDIeasRzo1ShCwQKTh0cyw//Cl136E7AmU4a/LArPe7UeEmsoOCVWXAdG7m9w'
    b'5MIcCqLpl9HgXqSgqPj3nxGY9nUnIvuc/oUdKeFOjNpRHxAMJZoHEQDDK4UZwS/yHgAAAABJ'
    b'RU5ErkJggg==')
index.append('toggle_off_24dp_1976d2_fill0_wght400_grad0_opsz24')
catalog['toggle_off_24dp_1976d2_fill0_wght400_grad0_opsz24'] = toggle_off_24dp_1976d2_fill0_wght400_grad0_opsz24

#----------------------------------------------------------------------
toggle_on_24dp_1976d2_fill0_wght400_grad0_opsz24 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAABQUlEQVRIS2NkoDFgpLH5DKMW'
    b'EAxh+geRZMmlIgYmhl6CTsOm4D9D0fNuvX5kKRQfSJZd+k+WwWiannfpwc2FM5AN///rr+KL'
    b'CYYPSLFMvOSiIhMT4z2YHpglYAskSi+VMTIydILYyLYTskCi7NJKoAFhYHX/GZYBgyca5tB/'
    b'//8XvOzWnwi2ACb48w+j3Ls+3ceEDIY46vImRsb/vihq/zNs/M/8t4DxH/N9mGNRLCDF9bji'
    b'C2QGTA7Epq8FX5hZRT63a74lKojKLu5gZGB0R1b7n+H/lv//GJKBkf0SJYjESy9VMDEytJMc'
    b'yaUXVzAyMoZDLVkODJIoeCQz/C982aU/AWsyZfjLovC8V+shMT6BqZGouK7A+O83OHKRHUq/'
    b'jAazmZKi4t9/RmDa152I7HP6F3akhDsxakd9QDCUaB5EAOcMiRnLYc5QAAAAAElFTkSuQmCC')
index.append('toggle_on_24dp_1976d2_fill0_wght400_grad0_opsz24')
catalog['toggle_on_24dp_1976d2_fill0_wght400_grad0_opsz24'] = toggle_on_24dp_1976d2_fill0_wght400_grad0_opsz24

#----------------------------------------------------------------------
update_24dp_1976d2_fill0_wght400_grad0_opsz24 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAACIElEQVRIS91VPUscURS9b3Y3'
    b'ZkliE3GcWClstdkxxVrYWSmEtAo2CfgHVHCHlIIWOhsx/yCgpZWFKCrYWURM3NnGQrCJ7KiB'
    b'INH9ctfneYsjs8PMG0OQBB8Mw8x7955z7tdj9MCLPbB/+vcA6kerm9VphTF63aSW09bFdXXk'
    b'93z6pywKwQqGeKSjK1/CgZjMASe6tM3UCyLGNcPCJ1HB1O/8+gK8nNjvfBJTfjiO+TWN2p/0'
    b'L24gdTI3rihswfl3cVlqe/4s3lAjB5jiilbM18VB0Fm1Tf2dTIGWyX0nxt64z0gBYFCEQRze'
    b'NwpZfdBt6BcCsd+RsXLIke6cDQSA7HbIPvHKdAy9AM63V2EgAJh8BZPeOrH3p2ZqyWv41wBB'
    b'IQhScJ8mbaqi/wAgX0JtPQXzCuIs3qHrjxQIb1rGKmPAtKDKKqiyJpDQRkOSd5HkNOf8g53t'
    b'WQyiB0dl7LXgqUKJeItSNWA7h97ZQ++kHdsmBerkIcq0GFimnp6ooMNn0OHTDWW3Y6KmRBJn'
    b's8lDX4BbJudg0sqJr9lmz9vQIAv2hrUDpn2YR+WCmYq7bXxnkauBNhGCARkIQrMNQv2N5jw6'
    b'iNLycGPMBCoQG23Gt1cxih47h6DGgJqs21DN5MYUxj47/2o8op1lk7aXjPTCuZtL0jjxYuFI'
    b'b6Vl3Bo+K/RGUyesbiXK1zEAE257kaMKuxr5NZc+l+GHAtwnyY8b4AaWfuAZx7C1rQAAAABJ'
    b'RU5ErkJggg==')
index.append('update_24dp_1976d2_fill0_wght400_grad0_opsz24')
catalog['update_24dp_1976d2_fill0_wght400_grad0_opsz24'] = update_24dp_1976d2_fill0_wght400_grad0_opsz24

