name: Build Debian Packages

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-debian:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - { name: "debian", version: "12", codename: "bookworm" }
          - { name: "debian", version: "13", codename: "trixie" }
          - { name: "ubuntu", version: "22.04", codename: "jammy" }
          - { name: "ubuntu", version: "24.04", codename: "noble" }
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build Debian package for ${{ matrix.distro.name }} ${{ matrix.distro.version }}
        uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          docker-image: ${{ matrix.distro.name }}:${{ matrix.distro.version }}
          buildpackage-opts: --build=binary --no-sign
          before-build-hook: |
            apt-get update
            apt-get install -y python3-dev python3-setuptools
            apt-get install -y python3-wxgtk4.0-dev || apt-get install -y python3-wxgtk-4.0-dev || apt-get install -y libwxgtk3.2-dev
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: yahac-${{ matrix.distro.name }}-${{ matrix.distro.version }}-${{ github.ref_name }}
          path: debian/artifacts/*.deb

  release:
    needs: build-debian
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v5
        
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: "**/*.deb"
          generate_release_notes: true